apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagios
  template:
    metadata:
      labels:
        app: nagios
    spec:
      containers:
      - name: nagios
        image: jasonrivers/nagios
        env:
          - name: NAGIOS_TIMEZONE
            value: 'America/New_York'
---
apiVersion: v1
kind: Service
metadata:
  name: nagios-nodeport
spec:
  type: NodePort
  selector:
    app: nagios
  ports:
    - nodePort: 30081
      port: 80
      targetPort: 80
