apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerta-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerta-web
  template:
    metadata:
      labels:
        app: alerta-web
    spec:
      containers:
      - name: alerta-web
        image: alerta/alerta-web
        env:
          - name: DATABASE_URL
            value: 'mongodb://mongodb:27017/monitoring'
---
apiVersion: v1
kind: Service
metadata:
  name: alerta-nodeport
spec:
  type: NodePort
  selector:
    app: alerta-web
  ports:
    - nodePort: 30080
      port: 8080
      targetPort: 8080
